#!/usr/bin/env python3
"""patala in-process from Python, through the UniFFI binding in ../../patala-py.

    python3 sdks/python/examples/direct_charge.py

There is no binding in this directory and there never will be one. `patala-py`
is the Python binding — generated by UniFFI from the single `#[uniffi::export]`
surface in `patala-uniffi` — and a second, hand-written one over `patala-ffi`'s
C ABI would be a worse copy of it: no typed errors, no enums, JSON in place of
records, and a second thing to keep in step with the core. This file is an
example OF that binding.

Everything here runs against `MockRail`: deterministic, offline, no credentials
and no network. patala is a payments library, so an example that moves real
value is not an example.

Build the binding first (from the workspace root):

    cargo build -p patala-py
    cargo run -p patala-py --bin uniffi-bindgen -- generate \
        --library target/debug/libpatala_py.dylib --language python \
        --out-dir patala-py/bindings/python
    cp target/debug/libpatala_py.dylib patala-py/bindings/python/

or `make smoke-python`, which does all of it. A `pip install`ed wheel works too
— this file only needs `import patala` to resolve.
"""

from __future__ import annotations

import os
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[3]


def _import_patala():
    """`import patala`, falling back to the in-tree generated bindings.

    A wheel built with maturin puts `patala` on the normal import path, so the
    plain import is tried first and an installed package always wins.
    """
    try:
        import patala  # noqa: PLC0415

        return patala, "import path"
    except ImportError:
        pass

    generated = REPO / "patala-py" / "bindings" / "python"
    if (generated / "patala.py").is_file():
        sys.path.insert(0, str(generated))
        import patala  # noqa: PLC0415

        return patala, str(generated)

    sys.exit(
        "could not import `patala`.\n"
        "Build the binding first — from the workspace root:\n"
        "    make smoke-python\n"
        "or see ../../patala-py/README.md for the four commands it runs.\n"
        f"(looked for {generated / 'patala.py'})"
    )


patala, source = _import_patala()

PatalaRail = patala.PatalaRail
PayRequest = patala.PayRequest
RailClass = patala.RailClass
DestinationStatus = patala.DestinationStatus
PatalaError = patala.PatalaError

checks = 0


def check(condition: bool, message: str) -> None:
    global checks
    checks += 1
    if not condition:
        sys.exit(f"FAILED: {message}")
    print(f"  ok  {message}")


def main() -> int:
    print(f"binding:  {source}")
    print(f"python:   {sys.version.split()[0]} on {sys.platform}")
    print(f"threads:  {_thread_count()} in this process before the first call\n")

    # A deterministic offline rail. `False` is `failing` — flip it to True to
    # exercise your error path against a rail where every operation fails.
    rail = PatalaRail.new_mock(
        "mock", RailClass.NON_CUSTODIAL_FINAL, ["USDC", "USD"], 0, False
    )

    print("capabilities")
    caps = rail.capabilities()
    check(rail.id() == "mock", f"id() == {rail.id()!r}")
    check(
        caps.rail_class == RailClass.NON_CUSTODIAL_FINAL,
        f"rail_class is {caps.rail_class} — a wallet address and a final receipt, not a card form",
    )
    check(not caps.holds_funds, "holds_funds is False — patala never holds funds")
    check(not caps.reversible, "reversible is False — there is no refund on this rail")
    check(caps.currencies == ["USDC", "USD"], f"currencies == {caps.currencies}")

    print("\npre-flight: validate_destination, before any money moves")
    verdict = rail.validate_destination("mock:wallet:alice")
    check(
        verdict.status == DestinationStatus.STRUCTURALLY_VALID,
        f"status is {verdict.status.name} for a well-formed address",
    )
    check(not verdict.is_refusal, "is_refusal is False — a field, never re-derived from status")
    check(
        verdict.human_must_confirm,
        "human_must_confirm is True even here — patala does not detect exchange addresses",
    )
    refused = rail.validate_destination("")
    check(
        refused.status == DestinationStatus.MALFORMED and refused.is_refusal,
        "an empty destination is a Malformed refusal, returned as a verdict and not raised",
    )

    print("\nquote -> charge -> verify")
    request = PayRequest(
        amount_minor=1250,
        currency="USDC",
        destination="mock:wallet:alice",
        reference="order-1",
    )
    quote = rail.quote(request)
    check(
        isinstance(quote.total_minor, int) and quote.total_minor == 1250,
        f"total_minor == {quote.total_minor} and is an int — minor units, never a float",
    )

    receipt = rail.charge(request)
    check(receipt.amount_minor == 1250, f"receipt.amount_minor == {receipt.amount_minor}")
    check(rail.verify(receipt), "the genuine receipt verifies True")

    tampered = patala.Receipt(
        rail_id=receipt.rail_id,
        amount_minor=receipt.amount_minor + 1,
        currency=receipt.currency,
        reference=receipt.reference,
        proof=receipt.proof,
        settled_at_unix=receipt.settled_at_unix,
    )
    check(
        rail.verify(tampered) is False,
        "a tampered receipt verifies False — fail-closed, and False is data, not an exception",
    )

    print("\nerrors are typed, never a crash")
    try:
        rail.charge(
            PayRequest(
                amount_minor=100, currency="EUR", destination="mock:wallet:alice",
                reference="order-2",
            )
        )
    except PatalaError.InvalidRequest as exc:
        check(True, f"an unsupported currency raised InvalidRequest: {exc}")
    else:
        sys.exit("FAILED: charging EUR on a USDC/USD rail should have raised")

    print(f"\nthreads:  {_thread_count()} after the whole round trip")
    print(f"\nALL {checks} PYTHON DIRECT ASSERTIONS PASSED")
    return 0


def _thread_count() -> int:
    """Threads in this process, counted by the OS rather than by Python.

    `threading.active_count()` only sees threads Python created, which is
    exactly the wrong number here: the question is whether the binding started
    any of its own.
    """
    try:
        with os.popen(f"ps -M {os.getpid()} 2>/dev/null | tail -n +2 | wc -l") as proc:
            return int(proc.read().strip())
    except (OSError, ValueError):
        return -1


if __name__ == "__main__":
    sys.exit(main())
